dist: trusty
sudo: required

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8

env:
  - DJANGO_VERSION=2.0.13
  - DJANGO_VERSION=2.1.15
  - DJANGO_VERSION=2.2.10
  - DJANGO_VERSION=3.0.3

before_install:
 - sudo apt-get update -y
 - sudo apt-get install -y libgdal-dev libproj-dev libproj-dev spatialite-bin python-dev python3-dev

install:
   # This is a dependency of our Django test script
 - CFLAGS=-I/usr/include/gdal pip install GDAL==1.10

 - pip install jsonfield Django==$DJANGO_VERSION
 - pip install coverage coveralls argparse flake8
 - python setup.py develop

before_script:
 - flake8 --ignore=E501,W504 djgeojson

script:
 - coverage run quicktest.py djgeojson

after_success:
 - coveralls

matrix:
    exclude:
        - python: 3.4
          env: DJANGO_VERSION=2.1.15
        - python: 3.4
          env: DJANGO_VERSION=2.2.10
        - python: 3.4
          env: DJANGO_VERSION=3.0.3
        - python: 3.5
          env: DJANGO_VERSION=3.0.3
        - python: 3.8
          env: DJANGO_VERSION=2.0.13
        - python: 3.8
          env: DJANGO_VERSION=2.1.15

