dist: trusty
sudo: required

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=1.11.17
  - DJANGO_VERSION=2.0.9
  - DJANGO_VERSION=2.1.4

before_install:
 - sudo apt-get update -y
 - sudo apt-get install -y libgdal-dev libproj-dev libproj-dev spatialite-bin python-dev python3-dev

install:
 - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then pip install git+git://github.com/tinio/pysqlite.git@extension-enabled#egg=pysqlite; fi
   # This is a dependency of our Django test script
 - CFLAGS=-I/usr/include/gdal pip install GDAL==1.10

 - pip install jsonfield Django==$DJANGO_VERSION
 - pip install coverage coveralls argparse flake8
 - python setup.py develop

before_script:
 - flake8 --ignore=E501,W504 djgeojson

script:
 - coverage run quicktest.py djgeojson

after_success:
 - coveralls

matrix:
    exclude:
        - python: 2.7
          env: DJANGO_VERSION=2.0.9
        - python: 2.7
          env: DJANGO_VERSION=2.1.4
        - python: 3.4
          env: DJANGO_VERSION=2.1.4
